# Generated by Django 4.2.3 on 2023-08-09 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statement',
        ),
    ]
